# Generated by Django 4.2.16 on 2024-09-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options_alter_post_options_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(
                default='images/campervan.jpg',
                upload_to='images/'),
        ),
    ]
